name: Qa test

on:
  pull_request:
    branches: [ "QA" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
    - name: Executar testes
      run: |
            coverage run -m teste_media_devops
          
    - name: Resultados
      run: coverage report